model_type: "BartChatbot"
max_steps: 128
min_length: 2
repetition_penalty: 1
context_template: >
  _setting_name {{ location_name }}

  _setting_desc {{ location }}</s>

  _self_name {{ name }}

  _self_persona {{ persona }}</s>

  _partner_name {{ other_name }}

  _other_persona {{ other_persona }}</s>

history_template: >
  
  {% for line in history -%}
  {%- if line.speaker == name -%}
  <speaker_self>
  {%- elif line.speaker == other_name -%}
  <speaker_other>
  {%- endif -%}
  {{- line.line -}}
  </s>

  {% endfor -%}

bos_token_id: 0
eos_token_id: 2
pad_token_id: 1

default_context: >
  {
    "location_name": "",
    "location": "",
    "name": "",
    "persona": "",
    "other_name": "",
    "other_persona": "",
    "history": [
      {"speaker": "", "line": ""}, 
      {"speaker": "", "line": ""}
    ]
  }